services:
  - type: web
    name: python-realtime-chat
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k eventlet -w 1 app:app"
    envVars:
      - key: SECRET_KEY
        value: "${SECRET_KEY}"
